# Generated by Django 4.2 on 2024-10-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_openinghoursmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghoursmodel',
            name='day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='openinghoursmodel',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
