# Generated by Django 4.2 on 2024-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_featuremodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
            ],
        ),
    ]
