# Generated by Django 4.2 on 2024-11-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_whowearelistmodel_whowearemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='WhoWeAreVideoModel/')),
            ],
        ),
    ]
